import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../providers/purchase_orders_provider.dart';

class POPdfGenerator {
  static Future<void> generateAndSharePO(PurchaseOrderDetail detail, {String lang = 'en'}) async {
    final pdf = pw.Document();

    final dict = {
      'fr': {'po': 'BON DE COMMANDE', 'desc': 'Description', 'qty': 'Qté', 'up': 'P.U.', 'total': 'Total', 'gen': 'Généré par SyncLedger'},
      'en': {'po': 'PURCHASE ORDER', 'desc': 'Description', 'qty': 'Qty', 'up': 'U.P.', 'total': 'Total', 'gen': 'Generated by SyncLedger'},
      'ar': {'po': 'طلب شراء', 'desc': 'الوصف', 'qty': 'الكمية', 'up': 'سعر الوحدة', 'total': 'المجموع', 'gen': 'تم الإنشاء بواسطة SyncLedger'}
    };
    final t = dict[lang]!;

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(t['po']!, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                    pw.Text('SyncLedger', style: pw.TextStyle(fontSize: 24, color: PdfColors.blueGrey)),
                  ],
                ),
              ),
              pw.SizedBox(height: 5),
              pw.Text('RC: 123456789 | NIF: 000123456789 | NIS: 123456789000123 | ART: 12B3456', 
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
              pw.SizedBox(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Vendor:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.grey600)),
                      pw.Text(detail.vendorName ?? 'N/A', style: pw.TextStyle(fontSize: 14)),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('PO #: ${detail.po.poNumber}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text('Date: ${detail.po.issuedAt != null ? DateFormat('yyyy-MM-dd').format(detail.po.issuedAt!) : '-'}'),
                      pw.Text('Status: ${detail.po.status.toUpperCase()}'),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 40),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey300),
                columnWidths: {
                  0: const pw.FlexColumnWidth(3),
                  1: const pw.FlexColumnWidth(1),
                  2: const pw.FlexColumnWidth(1.5),
                  3: const pw.FlexColumnWidth(1.5),
                },
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                    children: [
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(t['desc']!, style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(t['qty']!, textAlign: pw.TextAlign.center, style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(t['up']!, textAlign: pw.TextAlign.right, style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(t['total']!, textAlign: pw.TextAlign.right, style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                    ],
                  ),
                  ...detail.lineItems.map((item) {
                    final qty = (item['quantity'] as num?)?.toDouble() ?? 1.0;
                    final price = (item['unit_price'] as num?)?.toDouble() ?? 0.0;
                    final total = qty * price;
                    return pw.TableRow(
                      children: [
                        pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(item['description'] ?? '')),
                        pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(qty.toStringAsFixed(1), textAlign: pw.TextAlign.center)),
                        pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('${price.toStringAsFixed(2)} DZD', textAlign: pw.TextAlign.right)),
                        pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('${total.toStringAsFixed(2)} DZD', textAlign: pw.TextAlign.right)),
                      ],
                    );
                  }).toList(),
                ],
              ),
              pw.SizedBox(height: 10),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                children: [
                  pw.Text('${t['total']!}: ${detail.po.totalAmount.toStringAsFixed(2)} DZD', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                ]
              ),
              if (detail.po.notes != null && detail.po.notes!.isNotEmpty) ...[
                pw.SizedBox(height: 30),
                pw.Text('Notes:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.grey600)),
                pw.SizedBox(height: 5),
                pw.Text(detail.po.notes!, style: const pw.TextStyle(fontSize: 10)),
              ],
              pw.Spacer(),
              pw.Center(
                child: pw.Text(t['gen']!, style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey400)),
              ),
            ],
          );
        },
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'PO_${detail.po.poNumber}.pdf');
  }
}
