import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../domain/models/invoice_model.dart';

class PdfGenerator {
  static Future<void> generateAndShareInvoice(InvoiceModel invoice, {String lang = 'fr'}) async {
    final pdf = pw.Document();

    final dict = {
      'fr': {'invoice': 'FACTURE', 'payVia': 'Payer via', 'desc': 'Description', 'amt': 'Montant', 'total': 'Total TTC', 'gen': 'Généré par SyncLedger'},
      'en': {'invoice': 'INVOICE', 'payVia': 'Pay via', 'desc': 'Description', 'amt': 'Amount', 'total': 'Total TTC', 'gen': 'Generated by SyncLedger'},
      'ar': {'invoice': 'فاتورة', 'payVia': 'الدفع عبر', 'desc': 'الوصف', 'amt': 'المبلغ', 'total': 'المجموع', 'gen': 'تم الإنشاء بواسطة SyncLedger'}
    };
    final t = dict[lang]!;

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(invoice.documentType == 'quote' ? (lang == 'fr' ? 'DEVIS' : (lang == 'en' ? 'QUOTE' : 'عرض سعر')) : t['invoice']!, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                    pw.Text('SyncLedger', style: pw.TextStyle(fontSize: 24, color: PdfColors.blueGrey)),
                  ],
                ),
              ),
              pw.SizedBox(height: 5),
              pw.Text('RC: 123456789 | NIF: 000123456789 | NIS: 123456789000123 | ART: 12B3456', 
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
              pw.SizedBox(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('To:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text(invoice.vendorName),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('ID: #${invoice.id.substring(0, 8)}'),
                      pw.Text('Date: ${DateFormat('yyyy-MM-dd').format(invoice.date)}'),
                      pw.Text('Status: ${invoice.status.toUpperCase()}'),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 40),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey300),
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                    children: [
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(t['desc']!, style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(t['amt']!, textAlign: pw.TextAlign.right, style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                    ],
                  ),
                  pw.TableRow(
                    children: [
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Services Rendered')),
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('${invoice.amount.toStringAsFixed(2)} DZD', textAlign: pw.TextAlign.right)),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 10),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                children: [
                  pw.Text('${t['total']!}: ${invoice.amount.toStringAsFixed(2)} DZD', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                ]
              ),
              pw.Spacer(),
              if (invoice.paymentMethod == 'baridimob' || invoice.paymentMethod == 'wimpay')
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.start,
                  children: [
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('Pay via ${invoice.paymentMethod == 'baridimob' ? 'BaridiMob' : 'Wimpay'}:', style: pw.TextStyle(color: PdfColors.blueGrey, fontWeight: pw.FontWeight.bold)),
                        pw.SizedBox(height: 5),
                        pw.Container(
                          width: 80,
                          height: 80,
                          decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.blue)),
                          alignment: pw.Alignment.center,
                          child: pw.Text('[QR RIP]', style: const pw.TextStyle(fontSize: 10, color: PdfColors.blue)),
                        ),
                      ],
                    ),
                  ],
                ),
              pw.SizedBox(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.center,
                    children: [
                      pw.Text('Company Stamp & Signature:', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
                      pw.SizedBox(height: 10),
                      pw.Container(
                        width: 100,
                        height: 50,
                        decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey400)),
                        alignment: pw.Alignment.center,
                        child: pw.Text('[Cachet]', style: const pw.TextStyle(color: PdfColors.grey500)),
                      ),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.Container(
                alignment: pw.Alignment.center,
                child: pw.Text('Generated by SyncLedger', style: const pw.TextStyle(color: PdfColors.grey)),
              ),
            ],
          );
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'Invoice_${invoice.id.substring(0, 8)}.pdf',
    );
  }
}
